
import React, { useState, useMemo } from 'react';
import type { GeneratedProtocol } from '../types';

interface ProtocolViewerProps {
    protocol: GeneratedProtocol;
}

const ProtocolViewer: React.FC<ProtocolViewerProps> = ({ protocol }) => {
    const [activeSection, setActiveSection] = useState<string>('1.0');
    const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['1.0']));
    const outputs = protocol.protocol_outputs || [];
    const questions = protocol.questions_to_confirm || [];
    const contradictions = protocol.contradictions || [];
    const warnings = protocol.quality_checks?.consistency_warnings || [];

    // Group items into a hierarchy
    const tocTree = useMemo(() => {
        const groups: Record<string, any[]> = {};
        
        // Initialize top-level groups we expect
        const topLevels = [
            '1.0 Objectives', '2.0 Background', '3.0 Subjects', '4.0 Recruitment',
            '5.0 Consent', '6.0 HIPAA', '7.0 Design', '8.0 Statistics',
            '9.0 Data Monitoring', '10.0 Risks', '11.0 Benefits', '12.0 Sharing',
            '13.0 Payment', '14.0 Costs', '15.0 Resources', '16.0 Approvals',
            '17.0 Multi-Site', '18.0 Adverse Events', '19.0 Monitoring', '20.0 References',
            '21.0 Data Management', '22.0 Banking'
        ];

        topLevels.forEach(tl => {
            const [id] = tl.split(' ');
            groups[id] = [];
        });

        outputs.forEach(item => {
            const major = item.id.split('.')[0] + '.0';
            if (groups[major]) {
                groups[major].push(item);
            } else {
                // If it doesn't fit standard pattern, check if it IS a major header itself
                if (item.id.endsWith('.0')) {
                    if (!groups[item.id]) groups[item.id] = [];
                    // Don't push itself as a child if it's the header, unless we handle it specially
                } else {
                    // Fallback
                    const fallbackMajor = 'Other';
                    if (!groups[fallbackMajor]) groups[fallbackMajor] = [];
                    groups[fallbackMajor].push(item);
                }
            }
        });

        return groups;
    }, [outputs]);

    const toggleSection = (sectionId: string) => {
        const newSet = new Set(expandedSections);
        if (newSet.has(sectionId)) {
            newSet.delete(sectionId);
        } else {
            newSet.add(sectionId);
        }
        setExpandedSections(newSet);
    };

    const scrollToSection = (id: string) => {
        const el = document.getElementById(`section-${id}`);
        if (el) {
            el.scrollIntoView({ behavior: 'smooth', block: 'start' });
            setActiveSection(id);
        }
    };

    const handleDownload = () => {
        const preHtml = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
        <meta charset='utf-8'>
        <title>Protocol Draft</title>
        <style>
            body { font-family: 'Times New Roman', serif; font-size: 11pt; }
            h2 { font-size: 14pt; margin-top: 20px; }
            p { white-space: pre-wrap; margin-bottom: 12px; }
        </style>
        </head><body>
        <h1>HRP-591 Protocol Content Draft</h1>
        <p><i>Generated by LionIRB Assist</i></p>
        <hr/>`;

        const sectionsHtml = outputs.map(p => 
            `<h2>SECTION ${p.id}: ${p.label}</h2>
            <p>${p.paste_text.replace(/\n/g, '<br/>')}</p>
            <hr/>`
        ).join('');

        const postHtml = `</body></html>`;
        const fullHtml = preHtml + sectionsHtml + postHtml;

        const blob = new Blob(['\ufeff', fullHtml], { type: 'application/msword' });
        const url = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(fullHtml);
        
        const a = document.createElement('a');
        a.href = url;
        a.download = `HRP-591-Content-Draft.doc`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    };

    // Helper to get title for a major group (e.g. 1.0 -> Objectives)
    const getGroupTitle = (groupId: string) => {
        // Find a child to guess context or use static map
        // For now, static map logic embedded in useMemo keys, let's just make it readable
        const staticMap: Record<string, string> = {
            '1.0': 'Objectives', '2.0': 'Background', '3.0': 'Inclusion/Exclusion',
            '4.0': 'Recruitment', '5.0': 'Consent', '6.0': 'HIPAA', '7.0': 'Study Design',
            '8.0': 'Statistics', '9.0': 'Data Monitoring', '10.0': 'Risks', '11.0': 'Benefits',
            '12.0': 'Sharing Results', '13.0': 'Payment', '14.0': 'Economic Burden',
            '15.0': 'Resources', '16.0': 'Other Approvals', '17.0': 'Multi-Site',
            '18.0': 'Adverse Events', '19.0': 'Monitoring', '20.0': 'References',
            '21.0': 'Confidentiality', '22.0': 'Banking'
        };
        return staticMap[groupId] || `Section ${groupId}`;
    };

    return (
        <div className="flex flex-col lg:flex-row gap-8 py-8 animate-fadeIn h-[calc(100vh-140px)]">
            
            {/* Navigation Sidebar */}
            <div className="lg:w-1/4 flex-shrink-0">
                <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-4 sticky top-4 max-h-full overflow-y-auto custom-scrollbar flex flex-col h-[calc(100vh-180px)]">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 px-2">Table of Contents</h4>
                    <nav className="space-y-1 flex-1 overflow-y-auto pr-2 custom-scrollbar">
                        {Object.keys(tocTree).sort((a,b) => parseFloat(a) - parseFloat(b)).map((groupId) => {
                            const items = tocTree[groupId];
                            const isExpanded = expandedSections.has(groupId);
                            const hasChildren = items.length > 0;

                            if (!hasChildren) return null;

                            return (
                                <div key={groupId} className="mb-1">
                                    <button
                                        onClick={() => toggleSection(groupId)}
                                        className={`w-full text-left px-3 py-2 rounded-lg text-sm font-bold transition-colors flex items-center justify-between group ${
                                            activeSection.startsWith(groupId.replace('.0', '')) 
                                            ? 'text-[#1E407C] bg-blue-50' 
                                            : 'text-slate-700 hover:bg-slate-50'
                                        }`}
                                    >
                                        <div className="flex items-center">
                                            <span className="opacity-50 mr-2 w-8">{groupId}</span>
                                            <span className="truncate">{getGroupTitle(groupId)}</span>
                                        </div>
                                        <svg 
                                            className={`w-4 h-4 text-slate-400 transition-transform ${isExpanded ? 'rotate-90' : ''}`} 
                                            fill="none" viewBox="0 0 24 24" stroke="currentColor"
                                        >
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7" />
                                        </svg>
                                    </button>
                                    
                                    {isExpanded && (
                                        <div className="ml-4 mt-1 space-y-1 border-l-2 border-slate-100 pl-2">
                                            {items.map(item => (
                                                <button
                                                    key={item.id}
                                                    onClick={() => scrollToSection(item.id)}
                                                    className={`w-full text-left px-3 py-1.5 rounded-md text-xs font-medium transition-colors truncate ${
                                                        activeSection === item.id 
                                                        ? 'bg-[#1E407C] text-white' 
                                                        : 'text-slate-500 hover:text-slate-800 hover:bg-slate-50'
                                                    }`}
                                                    title={item.label}
                                                >
                                                    <span className="mr-2 opacity-70">{item.id}</span>
                                                    {item.label.replace(item.id, '').trim()}
                                                </button>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </nav>
                    <div className="mt-4 pt-4 border-t border-slate-100 px-2 flex-shrink-0">
                        <button 
                            onClick={handleDownload}
                            className="w-full bg-green-600 text-white text-xs font-bold py-3 rounded-lg shadow hover:bg-green-700 transition-colors flex items-center justify-center"
                        >
                            <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                            Download Word Doc
                        </button>
                    </div>
                </div>
            </div>

            {/* Content Area */}
            <div className="lg:w-3/4 overflow-y-auto custom-scrollbar pr-2 space-y-6 pb-20">
                
                {/* Diagnostics Panel */}
                {(questions.length > 0 || contradictions.length > 0 || warnings.length > 0) && (
                    <div className="bg-amber-50 border border-amber-100 rounded-2xl p-6 mb-4">
                        <h3 className="text-lg font-bold text-amber-900 mb-4 flex items-center">
                            <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                            Copilot Diagnostics
                        </h3>
                        <div className="grid md:grid-cols-2 gap-4">
                            {contradictions.length > 0 && (
                                <div className="bg-white p-4 rounded-xl border border-red-200 shadow-sm">
                                    <span className="text-xs font-bold text-red-600 uppercase tracking-widest block mb-2">Contradictions</span>
                                    <ul className="list-disc list-inside text-sm text-slate-700 space-y-1">
                                        {contradictions.map((c, i) => <li key={i}>{c}</li>)}
                                    </ul>
                                </div>
                            )}
                            {questions.length > 0 && (
                                <div className="bg-white p-4 rounded-xl border border-amber-200 shadow-sm">
                                    <span className="text-xs font-bold text-amber-600 uppercase tracking-widest block mb-2">To Confirm</span>
                                    <ul className="list-disc list-inside text-sm text-slate-700 space-y-1">
                                        {questions.map((q, i) => <li key={i}>{q}</li>)}
                                    </ul>
                                </div>
                            )}
                        </div>
                    </div>
                )}
                
                {/* Header Info */}
                <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 mb-4 flex items-center justify-between">
                    <div>
                        <h3 className="text-lg font-bold text-blue-900 mb-1">Protocol Draft Generated</h3>
                        <p className="text-blue-700 text-sm">Review the sections below. Text is formatted for the HRP-591 Word Document.</p>
                    </div>
                </div>
                
                {outputs.length === 0 ? (
                     <div className="bg-white border border-slate-200 rounded-2xl p-12 text-center">
                         <p className="text-slate-400 font-bold">No protocol sections were generated.</p>
                         <p className="text-slate-400 text-sm mt-2">Please try adjusting your inputs or check the diagnostics panel.</p>
                     </div>
                ) : (
                    outputs.map((item, idx) => (
                        <div 
                            key={idx} 
                            id={`section-${item.id}`}
                            className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm scroll-mt-4 group hover:border-[#1E407C]/30 transition-colors"
                        >
                            <div className="flex justify-between items-start mb-6 pb-4 border-b border-slate-100">
                                <div>
                                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-1">Section {item.id}</span>
                                    <h3 className="text-xl font-bold text-slate-900">{item.label}</h3>
                                </div>
                                <div className="flex items-center space-x-2">
                                     <span className="inline-block px-2 py-1 rounded text-[10px] font-bold uppercase bg-slate-100 text-slate-500">
                                        {item.shape.replace(/_/g, ' ')}
                                    </span>
                                    <button 
                                        className="p-2 hover:bg-[#1E407C] hover:text-white bg-slate-50 rounded-lg text-slate-400 transition-colors"
                                        onClick={() => {
                                            navigator.clipboard.writeText(item.paste_text);
                                        }}
                                        title="Copy Section Text"
                                    >
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                                    </button>
                                </div>
                            </div>

                            <div className="prose prose-slate max-w-none text-sm leading-relaxed whitespace-pre-wrap font-sans text-slate-700 bg-slate-50/50 p-6 rounded-xl border border-slate-100">
                                {item.paste_text}
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
};

export default ProtocolViewer;
